# Generated by Django 5.2.1 on 2025-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("npi", models.CharField(max_length=10, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("credential", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("affiliated_organizations", models.CharField(max_length=255)),
                ("practice_address_street", models.CharField(max_length=255)),
                ("practice_address_city", models.CharField(max_length=100)),
                ("practice_address_zip", models.CharField(max_length=10)),
                ("practice_address_state", models.CharField(max_length=50)),
                ("specialty_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="PredictionLog",
        ),
    ]
