# Generated by Django 5.2.1 on 2025-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialist", "0002_specialist_delete_predictionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialist",
            name="npi",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="practice_address_state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="practice_address_zip",
            field=models.CharField(max_length=20),
        ),
    ]
