# Generated by Django 5.2.1 on 2025-05-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_diseasecategory_specialist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialist",
            name="category",
        ),
        migrations.DeleteModel(
            name="DiseaseCategory",
        ),
        migrations.DeleteModel(
            name="Specialist",
        ),
    ]
